









  5%|â–Œ         | 10/189 [00:32<09:24,  3.16s/it][W 2023-07-09 18:39:21,549] Trial 0 failed with parameters: {'fc1_dim': 987, 'dropout_rate0': 0.5895433563743391, 'dropout_rate1': 0.2857978002940175, 'weight_decay': 2.73074423607381, 'lr': 0.00023431784914539817, 'warmup_steps': 572, 'per_batch_size': 23} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\user\OneDrive - Technion\GoodNotes\Semester 8\Deep Learning\project\code\HumanOrGPT\Models\BasedOnTrainer.py", line 185, in objective
    trainer.train()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\trainer.py", line 1645, in train
    return inner_training_loop(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\trainer.py", line 2759, in training_step
    loss = self.compute_loss(model, inputs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\trainer.py", line 2784, in compute_loss
    outputs = model(**inputs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\models\distilbert\modeling_distilbert.py", line 763, in forward
    distilbert_output = self.distilbert(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\models\distilbert\modeling_distilbert.py", line 583, in forward
    return self.transformer(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\models\distilbert\modeling_distilbert.py", line 359, in forward
    layer_outputs = layer_module(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\models\distilbert\modeling_distilbert.py", line 313, in forward
    ffn_output = self.ffn(sa_output)  # (bs, seq_length, dim)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\models\distilbert\modeling_distilbert.py", line 254, in forward
    return apply_chunking_to_forward(self.ff_chunk, self.chunk_size_feed_forward, self.seq_len_dim, input)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\pytorch_utils.py", line 237, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\models\distilbert\modeling_distilbert.py", line 257, in ff_chunk
    x = self.lin1(input)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
KeyboardInterrupt
[W 2023-07-09 18:39:21,629] Trial 0 failed with value None.
Traceback (most recent call last):
  File "C:\Users\user\OneDrive - Technion\GoodNotes\Semester 8\Deep Learning\project\code\HumanOrGPT\Models\BasedOnTrainer.py", line 231, in <module>
    custom_model_on_rephrased("../Datasets/Rephrased_GPT3_paper.xlsx", training_params=None, test_set_path=None, single_sentence=None)
  File "C:\Users\user\OneDrive - Technion\GoodNotes\Semester 8\Deep Learning\project\code\HumanOrGPT\Models\BasedOnTrainer.py", line 220, in custom_model_on_rephrased
    study_rephrased_paper.optimize(objective, n_trials=trials)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\optuna\study\study.py", line 443, in optimize
    _optimize(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\optuna\study\_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\optuna\study\_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\optuna\study\_optimize.py", line 251, in _run_trial
    raise func_err
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\user\OneDrive - Technion\GoodNotes\Semester 8\Deep Learning\project\code\HumanOrGPT\Models\BasedOnTrainer.py", line 185, in objective
    trainer.train()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\trainer.py", line 1645, in train
    return inner_training_loop(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\trainer.py", line 2759, in training_step
    loss = self.compute_loss(model, inputs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\trainer.py", line 2784, in compute_loss
    outputs = model(**inputs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\models\distilbert\modeling_distilbert.py", line 763, in forward
    distilbert_output = self.distilbert(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\models\distilbert\modeling_distilbert.py", line 583, in forward
    return self.transformer(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\models\distilbert\modeling_distilbert.py", line 359, in forward
    layer_outputs = layer_module(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\models\distilbert\modeling_distilbert.py", line 313, in forward
    ffn_output = self.ffn(sa_output)  # (bs, seq_length, dim)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\models\distilbert\modeling_distilbert.py", line 254, in forward
    return apply_chunking_to_forward(self.ff_chunk, self.chunk_size_feed_forward, self.seq_len_dim, input)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\pytorch_utils.py", line 237, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\models\distilbert\modeling_distilbert.py", line 257, in ff_chunk
    x = self.lin1(input)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
KeyboardInterrupt